/*
L3vels Api

Testing UtilitiesApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package l3vels-sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/chkhikvadze/l3vels-sdk"
)

func Test_l3vels-sdk_UtilitiesApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UtilitiesApiService Health", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.UtilitiesApi.Health(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
