/*
L3vels Api

L3vels API for Game developers

API version: 0.3
Contact: support@l3vels.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package l3vels-sdk

import (
	"encoding/json"
	"time"
)

// checks if the Project type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Project{}

// Project struct for Project
type Project struct {
	// The unique identifier for the Game entity.
	Id string `json:"id"`
	// The name of the Game.
	Name string `json:"name"`
	// A brief description of the Game.
	Description string `json:"description"`
	// The category or genre of the Game.
	Category string `json:"category"`
	// The logo or icon associated with the Game.
	LogoImage string `json:"logo_image"`
	// Additional images associated with the collection, such as screenshots or promotional images.
	Medias []string `json:"medias"`
	// Additional social links associated with the collection
	SocialLinks []string `json:"social_links"`
	// The main or featured image associated with the Game. You can set it from the Dashboard as main image.
	MainMedia string `json:"main_media"`
	// A unique URL for the game on the L3vels platform.
	Url string `json:"url"`
	// The URL for the Game's website or landing page.
	WebLink string `json:"web_link"`
	// The link to the Game's Discord server.
	Discord string `json:"discord"`
	// The link to the Game's official Twitter account.
	Twitter string `json:"twitter"`
	// The link to the Game's official Instagram account.
	Instagram string `json:"instagram"`
	//  A phone number for contacting the Game's developers or support team.
	ContactPhone string `json:"contact_phone"`
	// An email address for contacting the Game's developers or support team.
	ContactEmail string `json:"contact_email"`
	// The current status of the Game, such as \"Draft\", \"Active\", or \"Inactive\".
	Status string `json:"status"`
	//  The unique identifier of the account that the Game belongs to. This allows developers to manage multiple Games across multiple accounts.
	AccountId float32 `json:"account_id"`
	// The date and time that the Game entity was created.
	CreatedOn time.Time `json:"created_on"`
	// The date and time that the Game entity was last modified.
	ModifiedOn time.Time `json:"modified_on"`
	// The user or system that created the Game entity.
	CreatedBy float32 `json:"created_by"`
	// The user or system that last modified the Game entity.
	ModifiedBy float32 `json:"modified_by"`
}

// NewProject instantiates a new Project object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProject(id string, name string, description string, category string, logoImage string, medias []string, socialLinks []string, mainMedia string, url string, webLink string, discord string, twitter string, instagram string, contactPhone string, contactEmail string, status string, accountId float32, createdOn time.Time, modifiedOn time.Time, createdBy float32, modifiedBy float32) *Project {
	this := Project{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.Category = category
	this.LogoImage = logoImage
	this.Medias = medias
	this.SocialLinks = socialLinks
	this.MainMedia = mainMedia
	this.Url = url
	this.WebLink = webLink
	this.Discord = discord
	this.Twitter = twitter
	this.Instagram = instagram
	this.ContactPhone = contactPhone
	this.ContactEmail = contactEmail
	this.Status = status
	this.AccountId = accountId
	this.CreatedOn = createdOn
	this.ModifiedOn = modifiedOn
	this.CreatedBy = createdBy
	this.ModifiedBy = modifiedBy
	return &this
}

// NewProjectWithDefaults instantiates a new Project object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectWithDefaults() *Project {
	this := Project{}
	return &this
}

// GetId returns the Id field value
func (o *Project) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Project) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Project) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Project) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Project) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Project) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *Project) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *Project) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *Project) SetDescription(v string) {
	o.Description = v
}

// GetCategory returns the Category field value
func (o *Project) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *Project) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *Project) SetCategory(v string) {
	o.Category = v
}

// GetLogoImage returns the LogoImage field value
func (o *Project) GetLogoImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LogoImage
}

// GetLogoImageOk returns a tuple with the LogoImage field value
// and a boolean to check if the value has been set.
func (o *Project) GetLogoImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogoImage, true
}

// SetLogoImage sets field value
func (o *Project) SetLogoImage(v string) {
	o.LogoImage = v
}

// GetMedias returns the Medias field value
func (o *Project) GetMedias() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Medias
}

// GetMediasOk returns a tuple with the Medias field value
// and a boolean to check if the value has been set.
func (o *Project) GetMediasOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Medias, true
}

// SetMedias sets field value
func (o *Project) SetMedias(v []string) {
	o.Medias = v
}

// GetSocialLinks returns the SocialLinks field value
func (o *Project) GetSocialLinks() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SocialLinks
}

// GetSocialLinksOk returns a tuple with the SocialLinks field value
// and a boolean to check if the value has been set.
func (o *Project) GetSocialLinksOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SocialLinks, true
}

// SetSocialLinks sets field value
func (o *Project) SetSocialLinks(v []string) {
	o.SocialLinks = v
}

// GetMainMedia returns the MainMedia field value
func (o *Project) GetMainMedia() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MainMedia
}

// GetMainMediaOk returns a tuple with the MainMedia field value
// and a boolean to check if the value has been set.
func (o *Project) GetMainMediaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MainMedia, true
}

// SetMainMedia sets field value
func (o *Project) SetMainMedia(v string) {
	o.MainMedia = v
}

// GetUrl returns the Url field value
func (o *Project) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *Project) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *Project) SetUrl(v string) {
	o.Url = v
}

// GetWebLink returns the WebLink field value
func (o *Project) GetWebLink() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebLink
}

// GetWebLinkOk returns a tuple with the WebLink field value
// and a boolean to check if the value has been set.
func (o *Project) GetWebLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebLink, true
}

// SetWebLink sets field value
func (o *Project) SetWebLink(v string) {
	o.WebLink = v
}

// GetDiscord returns the Discord field value
func (o *Project) GetDiscord() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Discord
}

// GetDiscordOk returns a tuple with the Discord field value
// and a boolean to check if the value has been set.
func (o *Project) GetDiscordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Discord, true
}

// SetDiscord sets field value
func (o *Project) SetDiscord(v string) {
	o.Discord = v
}

// GetTwitter returns the Twitter field value
func (o *Project) GetTwitter() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Twitter
}

// GetTwitterOk returns a tuple with the Twitter field value
// and a boolean to check if the value has been set.
func (o *Project) GetTwitterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Twitter, true
}

// SetTwitter sets field value
func (o *Project) SetTwitter(v string) {
	o.Twitter = v
}

// GetInstagram returns the Instagram field value
func (o *Project) GetInstagram() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Instagram
}

// GetInstagramOk returns a tuple with the Instagram field value
// and a boolean to check if the value has been set.
func (o *Project) GetInstagramOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instagram, true
}

// SetInstagram sets field value
func (o *Project) SetInstagram(v string) {
	o.Instagram = v
}

// GetContactPhone returns the ContactPhone field value
func (o *Project) GetContactPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContactPhone
}

// GetContactPhoneOk returns a tuple with the ContactPhone field value
// and a boolean to check if the value has been set.
func (o *Project) GetContactPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContactPhone, true
}

// SetContactPhone sets field value
func (o *Project) SetContactPhone(v string) {
	o.ContactPhone = v
}

// GetContactEmail returns the ContactEmail field value
func (o *Project) GetContactEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContactEmail
}

// GetContactEmailOk returns a tuple with the ContactEmail field value
// and a boolean to check if the value has been set.
func (o *Project) GetContactEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContactEmail, true
}

// SetContactEmail sets field value
func (o *Project) SetContactEmail(v string) {
	o.ContactEmail = v
}

// GetStatus returns the Status field value
func (o *Project) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Project) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Project) SetStatus(v string) {
	o.Status = v
}

// GetAccountId returns the AccountId field value
func (o *Project) GetAccountId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *Project) GetAccountIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *Project) SetAccountId(v float32) {
	o.AccountId = v
}

// GetCreatedOn returns the CreatedOn field value
func (o *Project) GetCreatedOn() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedOn
}

// GetCreatedOnOk returns a tuple with the CreatedOn field value
// and a boolean to check if the value has been set.
func (o *Project) GetCreatedOnOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedOn, true
}

// SetCreatedOn sets field value
func (o *Project) SetCreatedOn(v time.Time) {
	o.CreatedOn = v
}

// GetModifiedOn returns the ModifiedOn field value
func (o *Project) GetModifiedOn() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ModifiedOn
}

// GetModifiedOnOk returns a tuple with the ModifiedOn field value
// and a boolean to check if the value has been set.
func (o *Project) GetModifiedOnOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedOn, true
}

// SetModifiedOn sets field value
func (o *Project) SetModifiedOn(v time.Time) {
	o.ModifiedOn = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *Project) GetCreatedBy() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *Project) GetCreatedByOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *Project) SetCreatedBy(v float32) {
	o.CreatedBy = v
}

// GetModifiedBy returns the ModifiedBy field value
func (o *Project) GetModifiedBy() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ModifiedBy
}

// GetModifiedByOk returns a tuple with the ModifiedBy field value
// and a boolean to check if the value has been set.
func (o *Project) GetModifiedByOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedBy, true
}

// SetModifiedBy sets field value
func (o *Project) SetModifiedBy(v float32) {
	o.ModifiedBy = v
}

func (o Project) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Project) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["category"] = o.Category
	toSerialize["logo_image"] = o.LogoImage
	toSerialize["medias"] = o.Medias
	toSerialize["social_links"] = o.SocialLinks
	toSerialize["main_media"] = o.MainMedia
	toSerialize["url"] = o.Url
	toSerialize["web_link"] = o.WebLink
	toSerialize["discord"] = o.Discord
	toSerialize["twitter"] = o.Twitter
	toSerialize["instagram"] = o.Instagram
	toSerialize["contact_phone"] = o.ContactPhone
	toSerialize["contact_email"] = o.ContactEmail
	toSerialize["status"] = o.Status
	toSerialize["account_id"] = o.AccountId
	toSerialize["created_on"] = o.CreatedOn
	toSerialize["modified_on"] = o.ModifiedOn
	toSerialize["created_by"] = o.CreatedBy
	toSerialize["modified_by"] = o.ModifiedBy
	return toSerialize, nil
}

type NullableProject struct {
	value *Project
	isSet bool
}

func (v NullableProject) Get() *Project {
	return v.value
}

func (v *NullableProject) Set(val *Project) {
	v.value = val
	v.isSet = true
}

func (v NullableProject) IsSet() bool {
	return v.isSet
}

func (v *NullableProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProject(val *Project) *NullableProject {
	return &NullableProject{value: val, isSet: true}
}

func (v NullableProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


